Change naming of form questions
fossasia/eventyay-talk pull request #31
Opened 2024-02-12 19:13 UTC by Aryan20

Form questions:

Change naming ->
1. “Choose one from a list” to “Radio button (Choose one option)” 
2. “Choose multiple from a list” to “Checkbox (Choose one or several options)”

This is done to better reflect what these options do.

fixes: #12

![image](https://github.com/fossasia/eventyay-talk/assets/34372791/a2e9fa10-3314-4508-bbe8-a84882348736)

## Checklist

- [ ] I have added tests to cover my changes.
- [ ] I have updated the documentation.
- [ ] My change is listed in the ``doc/changelog.rst``.

2024-02-12 19:13 UTC, Aryan20 commented
Do I also need to update changelogs and docs?

2024-02-12 19:26 UTC, mariobehling commented
> Do I also need to update changelogs and docs?

yes, please

2024-02-14 00:27 UTC, mariobehling requested changes
There are a lot of unrelated PO file changes in this PR that should not be there.

2024-02-15 20:13 UTC, Aryan20 commented
Done, apologies for the delay

2024-02-15 22:31 UTC, mariobehling approved these changes

2024-02-16 01:32 UTC, norbusan commented
@mariobehling are you fine with the renaming? I am not sure which of those is actually better understandable.
Other than this, if we merge this change, we loose all the translations of this text, which by itself even worse.
So I am not convinced.

2025-06-04 12:00 UTC, hpdang commented
@Aryan20 do you want to solve the conflicts so we can merge this PR?

2025-06-04 13:52 UTC, mariobehling commented
> @mariobehling are you fine with the renaming? I am not sure which of those is actually better understandable. Other than this, if we merge this change, we loose all the translations of this text, which by itself even worse. So I am not convinced.

Yes, I am fine with it, cause it makes more sense and we also used this in the last eventyay version. Translations are not a big deal. Firstly they are also included in this commit and secondly such simple things can be taken care of by AI as we move forward.

2025-06-04 13:57 UTC, mariobehling commented
Sorry, I missed this. @Aryan20 Actually the translations are not included. Do you think you could do this using AI?

2025-12-02 20:48 UTC, closed without merging