Rename CfP to Call for Speakers in organiser view sidebar
fossasia/eventyay-talk pull request #33
Opened 2024-02-12 19:41 UTC by Aryan20

For better clarity, instead of using the acronym "CfP" we can instead use "Call for Speakers" directly.

fixes: #9

![image](https://github.com/fossasia/eventyay-talk/assets/34372791/5c382672-4984-4be9-a2ce-812586804de6)

## Checklist

- [ ] I have added tests to cover my changes.
- [ ] I have updated the documentation.
- [x] My change is listed in the ``doc/changelog.rst``.

2024-02-12 19:42 UTC, Aryan20 commented
Didn't find any documentation changes to do. Please check if the changelog is done properly, if so will apply similarly to my other PRs.
Thanks!

2024-02-12 19:56 UTC, mariobehling requested changes
There are a lot of changes to PO files in all kinds of languages. I assume it is autotranslated. Please make translations in a separate PR and only commit languages you know yourself.

2024-02-13 20:03 UTC, Aryan20 commented
Done. Is it okay now? If so I will do the same for the other PR as well. Thanks!

2024-02-14 00:25 UTC, mariobehling approved these changes

2024-02-14 00:25 UTC, merged

2024-02-18 10:24 UTC, marcoag commented
This is not a feature. @Aryan20, moving forward let's not make an entry on the changelog for every single change we made, plz.

2024-02-18 11:06 UTC, Aryan20 commented
> This is not a feature. @Aryan20, moving forward let's not make an entry on the changelog for every single change we made, plz.

Sure, I did it only because I was specifically told so in another PR and I did ask through comment on this one.
Also, if that is the case then we should update the issue template as that is contradictory and gives the message that it is required.
Won't do for other PRs.