rename mail and change order
fossasia/eventyay-talk pull request #35
Opened 2024-02-13 13:50 UTC by Kaushik-Iyer

This PR closes/references issue #11 

## How has this been tested?
Not tested yet, its just reordering and text changes s

## Checklist
- [ ] I have added tests to cover my changes.
- [ ] I have updated the documentation.
- [ ] My change is listed in the ``doc/changelog.rst``.

2024-02-14 03:28 UTC, Kaushik-Iyer commented
@mariobehling I have deployed and added a screenshot above. Please have a look, thank you

2024-02-15 13:42 UTC, marcoag requested changes

2024-02-15 13:42 UTC, marcoag commented on src/pretalx/locale/ca/LC_MESSAGES/django.po
>  msgstr ""
```suggestion
msgstr "Compose"
```

2024-02-15 13:42 UTC, marcoag commented on src/pretalx/locale/ca/LC_MESSAGES/django.po
>  msgstr ""
```suggestion
msgstr "Sent"
```

2024-02-15 13:42 UTC, marcoag commented on src/pretalx/locale/ca/LC_MESSAGES/django.po
>  msgstr ""
```suggestion
msgstr "Templates"
```

2024-02-15 13:42 UTC, marcoag commented on src/pretalx/locale/es_MX/LC_MESSAGES/django.po
>  msgstr ""
```suggestion
msgstr "Redactar"
```

2024-02-15 13:42 UTC, marcoag commented on src/pretalx/locale/es_MX/LC_MESSAGES/django.po
>  msgstr ""
```suggestion
msgstr "Enviar"
```

2024-02-15 13:42 UTC, marcoag commented on src/pretalx/locale/es_MX/LC_MESSAGES/django.po
>  msgstr ""
```suggestion
msgstr "Plantillas"
```

2024-02-15 13:42 UTC, marcoag commented on src/pretalx/locale/id/LC_MESSAGES/django.po
>  msgstr ""
```suggestion
msgstr "Kirim"
```

2024-02-15 13:42 UTC, marcoag commented on src/pretalx/locale/id/LC_MESSAGES/django.po
>  msgstr ""
```suggestion
msgstr "Menyusun"
```

2024-02-15 13:42 UTC, marcoag commented on src/pretalx/locale/id/LC_MESSAGES/django.po
>  msgstr ""
```suggestion
msgstr "Templats"
```

2024-02-15 13:42 UTC, marcoag commented on src/pretalx/locale/pt_BR/LC_MESSAGES/django.po
> +msgstr "emails enviados"
```suggestion
msgstr "Emails enviados"
```

2024-02-15 13:42 UTC, marcoag commented on src/pretalx/locale/cs/LC_MESSAGES/django.po
> +msgstr "Poslání e-mailu"
Let's just have consistency and use "email":
```suggestion
msgstr "Poslání emailu"
```

2024-02-15 13:42 UTC, marcoag commented on src/pretalx/locale/cs/LC_MESSAGES/django.po
> +msgstr "Odeslané e-maily"
```suggestion
msgstr "Odeslané emaily"
```

2024-02-15 13:42 UTC, marcoag commented on src/pretalx/locale/de_DE/LC_MESSAGES/django.po
> +msgstr "Verschickte E-Mails"
```suggestion
msgstr "Verschickte emails"
```

2024-02-15 13:42 UTC, marcoag commented on src/pretalx/locale/de_Formal/LC_MESSAGES/django.po
> +msgstr "E-Mails schreiben"
```suggestion
msgstr "Emails schreiben"
```

2024-02-15 13:42 UTC, marcoag commented on src/pretalx/locale/de_Formal/LC_MESSAGES/django.po
> +msgstr "Verschickte E-Mails"
```suggestion
msgstr "Verschickte emails"
```

2024-02-15 13:42 UTC, marcoag commented on src/pretalx/locale/el/LC_MESSAGES/django.po
> +msgstr "Σύνταξη e-mail"
```suggestion
msgstr "Σύνταξη email"
```

2024-02-15 13:42 UTC, marcoag commented on src/pretalx/locale/nl/LC_MESSAGES/django.po
> +msgstr "Schrijf E-mails"
```suggestion
msgstr "Schrijf emails"
```

2024-02-15 13:42 UTC, marcoag commented on src/pretalx/locale/nl/LC_MESSAGES/django.po
> +msgstr "Verstuur E-mails"
```suggestion
msgstr "Verstuur emails"
```

2024-02-15 13:42 UTC, marcoag commented on src/pretalx/locale/pt_PT/LC_MESSAGES/django.po
> +msgstr "Compor e-mails"
```suggestion
msgstr "Compor emails"
```

2024-02-15 13:42 UTC, marcoag commented on src/pretalx/locale/pt_PT/LC_MESSAGES/django.po
> +msgstr "E-mails Enviados"
```suggestion
msgstr "Emails enviados"
```

2024-02-16 06:25 UTC, Kaushik-Iyer commented
@mariobehling  @marcoag I have committed all the suggestions. But there are merge conflicts. I think the code lines mentioned in the files have been updated. You might want to have a look at one of the conflict files. Should I solve the merge conflicts also?

2024-02-16 07:02 UTC, norbusan commented
Yes, please merge the `main` branch into your branch, that is the normal procedure. Thanks

2024-02-16 08:11 UTC, Kaushik-Iyer commented
@norbusan I've tried to merge changes but this PR now looks really ugly. I'm assuming I need to create a new PR for the development branch instead of the main branch, or did I do something wrong?

2024-02-16 08:16 UTC, norbusan commented
Yes please, since and main and development are more or less the same, I suggest re-opening a new PR against development from the same branch. If you do this, please close this PR.

2024-02-16 08:21 UTC, Kaushik-Iyer commented
Re-opened new PR against development branch. Closing this PR now

2024-02-16 08:21 UTC, closed without merging