Rename mail and change order
fossasia/eventyay-talk pull request #44
Opened 2024-02-16 08:20 UTC by Kaushik-Iyer

This PR closes/references issue #11 

## How has this been tested?
Results on running the server locally are:

![image](https://github.com/fossasia/eventyay-talk/assets/84177184/07eed498-7909-4bfd-8c32-07e51843974a)

## Checklist
- [ ] I have added tests to cover my changes.
- [ ] I have updated the documentation.
- [ ] My change is listed in the ``doc/changelog.rst``.

2024-02-22 06:22 UTC, Kaushik-Iyer commented
Do I have to change anything in this PR? @marcoag

2024-02-22 06:51 UTC, marcoag commented
Yes, I think some suggestion I made on https://github.com/fossasia/eventyay-talk/pull/35 might have not been applied here, so please have a look, i.e.: e-mail or email consistency (choose one and use it through the changes)
- Review Portuguese from protugal, doesn't seem right.
- I see a change for `{% translate "Message Center" %}` but no change of `Message Center` on any translation, shouldn't this come along with changes on the `.po` files?

2024-02-22 06:52 UTC, marcoag requested changes
Requesting changes, please take a look at my comment above.

2024-02-22 07:02 UTC, Kaushik-Iyer commented
I'm pretty sure I had implemented all of your suggestion in the previous PR, but I'll still have a look. But for changing email/mail translation and the message center, how do I decide what's right? should I just google translate and make the change?

2024-02-22 07:49 UTC, marcoag commented
You're mixing thins:

- for e-mail/email is a suggestion I made on the previous PR: there's multiple uses of e-mail and email, both are correct but you should stick to one through all the translations. Maybe check what's on the other translations and use that one.

Since you missed this suggestion I asked you to also double check no others are missing here.

- for the message center you are changing this:
```
-                                        {% translate "Mails" %}
+                                        {% translate "Message Center" %}
```

Which basically changes the translation `msgid` `Mails` to `Message Center`. I am assuming this should come with changes on the `.po` files so what was being translated as `Mails` should also now be translated as `Message Center`. Also be careful and check through the code base for other instances of `Mails` as they will have to  be changed to `Message Center`.

2024-02-22 07:50 UTC, marcoag commented
For the Portuguese from portugal weird translation you can probably use some decent online translation tool.

2024-02-22 08:28 UTC, Kaushik-Iyer commented
online tools are suggesting the same translations for Portuguese (Portugal), except some which suggest 'Redigir Emails' instead of 'Compor Emails' for Compose. And as for the discrepancy between email and e-mail, even other translations are very random between the two

2024-02-22 12:11 UTC, marcoag commented
Ok for portuguese.

For the e-email vs email check the most common one around and use that one in this PR, at least lets start to be consistant as long as we can.

Also please check for other appearances of the modified `msgid`s around the codebase, if there are appearances they will have to also be changed.

2024-02-25 08:42 UTC, Kaushik-Iyer commented
I checked and saw email is more common, so used email in my changes.
checked for other occurrences of msgid "Mails" and changed them to message center as well, and solved conflicts

2024-02-28 10:53 UTC, Kaushik-Iyer commented
@marcoag anything else to be changed?

2025-10-09 18:58 UTC, mariobehling commented
We have merged this into eventyay-tickets. Hence closing this PR. Please contribute to eventyay-tickets.

2025-10-09 18:58 UTC, closed without merging